### ISSUE TITLE
Double social postings when doing bulk review

### ISSUE THREAD

**Issue by archangelic** [tildetown/tildetown-admin#26]
Whenever a bulk review of new users is done, there are 2 posts: one noting the individual user, and one bulk message.

this is caused by `post_single_user_social` being ran in `on_townie_pre_save` and then the `bulk_review` function running `post_users_to_social`

Is there a way to tell `on_townie_pre_save` to not run the posting function if we do bulk add?

**Comment by vilmibm** [comment]
thanks for filing the issue! i'm looking at it now.

i might just take it out for the pre_save. an admin just needs to remember that if they want the social announcement, they need to use the bulk action.

I'm in favor though of keeping the post_single_user_to_social function around. Usually I'd delete unused code but it might come in handy / is good example code for contributors to see.
