### ISSUE TITLE
Support self-service chsh and chfn

### ISSUE THREAD

**Issue by vilmibm** [tildetown/tildetown-admin#29]
This issue covers:

- [ ] An auth system that doesn't require a password but lets a user call chsh and chfn for themselves
- [ ] The actual implementation of those features

I'm not really sure yet how this should work or how it should be exposed. it's possible that we just want to wrap chsh and chfn with something and not involve the django admin at all.

**Comment by ghost** [comment]
I think the easiest way to do this would be to make the user make a file with a name of `~/.chsh` or something of the line with the contents of the desired shell, with a crontab entry to change the shell for respective users and then remove the .chsh file so it won't be redundantly changing the shell.

**Comment by ghost** [comment]
(bonus points: write a `chsh` in /usr/local/bin or something similar, that creates a `~/.chsh` instead of the usual chsh binary)

**Comment by vilmibm** [comment]
chatted with eq about this in irc, are going to try [this](https://serverfault.com/questions/202468/changing-the-shell-using-chsh-via-the-command-line-in-a-script#435539)

**Comment by vilmibm** [comment]
Fixed, used pam.d rules.
